image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          - apt update
          - apt -y install wget lsb-release gnupg
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt-get update
          - apt-get -y install cmake build-essential curl git mercurial libprotobuf-dev protobuf-compiler libprotoc-dev g++-8 ruby cppcheck
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          - gcc -v
          - g++ -v
          - gcov -v
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git -b v1.14
          - cd lcov
          - make install
          - cd ..
          # Dependency: Ignition packages
          - apt-get -y install
            libignition-cmake2-dev libignition-tools-dev libignition-math6-dev
          # Ignition msgs
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage -DCMAKE_INSTALL_PREFIX=/usr
          - make -j4
          - make test ARGS="-V" CTEST_OUTPUT_ON_FAILURE=1
          - make coverage
          # Use a special version of codecov for handling gcc8 output.
          - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov) -X gcovout -X gcov 2>/dev/null
          - make codecheck
          - make install
